name: 'Fake easy MACH deploy'
description: 'The eAsIeSt way to deploy MACH composer configurations'

inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
